import { ReactNode } from 'react';
import type { Metadata } from 'next';

import { ChatProvider, MainProvider } from '@/context';
import StyledComponentsRegistry from '@/lib/registry';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MainProvider>
          <ChatProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </ChatProvider>
        </MainProvider>
      </body>
    </html>
  );
}
