name: Stylelint

on:
  pull_request:
    branches-ignore:
      - 'doc/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Stylelint
        run: npx stylelint '**/*.{css,ts,tsx}'
